from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='admin-home'),
    path('user/', views.user, name='admin-user-list'),
    path('user-update/<str:ref>/',  views.updateUser, name='admin-user-update'),
    path('user-ban/<str:ref>/',  views.banUser, name='admin-user-ban'),
    path('create-trader/', views.createTrader, name='admin-create-trader'),
    path('update-trader/<str:ref>/', views.updateTrader, name='admin-update-trader'),
    path('delete-trader/<str:ref>/', views.deleteTrader, name='admin-delete-trader'),
    path('trader/', views.trader, name='admin-trader'),
    path('payment-method/create/', views.paymentMethod, name='admin-payment-method'),
    path('payment-method/update/<str:ref>/', views.updatePaymentMethod, name='admin-update-payment-method'),
    path('payment-method/delete/<str:ref>/', views.deletePaymentMethod, name='admin-delete-payment-method'),
    path('payment/', views.payment, name='admin-payment'),
    path('payment-approve/<str:ref>/', views.paymentApprove, name='admin-payment-approve'),
    path('plan/', views.plan, name='admin-plan'),
    path('trading-plan/update/<str:ref>/', views.tradingPlan, name='admin-trading-plan'),
    path('mining-plan/update/<str:ref>/', views.miningPlan, name='admin-mining-plan'),
    path('trading-plan/', views.listTradingPlan, name='admin-list-trading-plan'),
    path('mining-plan/', views.listMiningPlan, name='admin-list-mining-plan'),
    path('create-admin/', views.createAdmin, name='admin-super-admin'),
    path('stop-trade/<str:ref>/', views.adminCancelTrade, name='admin-cancel-trade'),
    path('add-coin/', views.addCoin, name='admin-add-coin'),
    path('add-coin-more/', views.addCoinPic, name='admin-add-coin-pic'),
    path('remove-trade/<str:ref>/', views.removeTrade, name='admin-remove-trade'),
    path('get-crypto/', views.addCrypto, name='admin-add-crypto'),
    path('get-crypto-all/', views.addCryptoPic, name='admin-add-crypto-all'),
    path('set-coin/', views.setCoin, name='admin-set-coin'),
    path('set-coin-add/<str:ref>/', views.setCoinAdd, name='admin-set-coin-add'),
    path('set-crypto-add/<str:ref>/', views.setCryptoAdd, name='admin-set-crypto-add'),
    path('set-forex-add/<str:ref>/', views.setForexAdd, name='admin-set-forex-add'),
    path('withdrawal/', views.withdrawal, name='admin-withdrawal'),
    path('withdrawal-approve/<str:ref>/', views.withdrawalApprove, name='admin-withdrawal-approve'),
    path('withdrawal-declined/<str:ref>/', views.withdrawalDeclined, name='admin-withdrawal-declined'),
]
