# Generated by Django 4.1.7 on 2023-03-29 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 8, 16, 49, 92980)),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 9, 16, 49, 92980)),
        ),
    ]
