# Generated by Django 4.1.7 on 2023-03-29 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_deposite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 15, 50, 6, 111912)),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 16, 50, 6, 111912)),
        ),
    ]
