# Generated by Django 4.1.7 on 2023-03-29 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_deposite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 22, 6, 13, 400496)),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 23, 6, 13, 400496)),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
