# Generated by Django 4.1.7 on 2023-03-30 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_deposite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='deposite',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 9, 23, 40, 982462)),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 10, 23, 40, 982462)),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='image',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='prove'),
        ),
    ]
