# Generated by Django 4.1.7 on 2023-03-30 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_deposite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 9, 42, 22, 470340)),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 10, 42, 22, 470340)),
        ),
    ]
