# Generated by Django 4.1.7 on 2023-03-30 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_deposite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 10, 9, 13, 933864), null=True),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='expire_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 11, 9, 13, 933864), null=True),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.currency'),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
