from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('pricing/', views.pricing, name='pricing'),
    path('market/', views.market, name='market'),
    path('deposite/list/', views.depositeList, name='depositelist'),
    path('account/', views.account, name='account'),
    path('refferals/', views.refferals, name='refferals'),
    path('withdrawals/', views.withdrawals, name='withdrawals'),
    path('buy/', views.buy, name='buy'),
    path('crypto/', views.crypto, name='crypto'),
    path('traders/', views.traders, name='traders'),
    path('cancel-trade/<str:ref>/', views.cancelTrade, name='cancel-trade'),
    path('copy-trade/<str:ref>/', views.copyTrade, name='copy-trade'),
    path('deposite/trading/', views.tradingPlans, name='tradingplan'),
    path('deposite/mining/', views.miningPlans, name='miningplan'),
    path('withdrawal/list/', views.selectWithdrawal, name='selectwithdrawal'),
    path('user/auth/email/', views.updateEmail, name='updateemail'),
    path('user/auth/photo/', views.updatePhoto, name='updatephoto'),
    path('user/auth/password/', views.updatePassword, name='updatepassword'),
    path('settings/', views.settings, name='settings'),
    path('profile/', views.profile, name='profile'),
    path('notifications/', views.notifications, name='notification'),
    path('verifications/', views.verification, name='verification'),
    path('identity/', views.identity, name='identity'),
    path('address/', views.address, name='address'),
    path('bank/', views.bank, name='bank'),
    path('crypto-withdrawal/', views.cryptoWithdrawal, name='crypto-withdrawal'),
    path('paypal/', views.paypal, name='paypal'),
    path('cashapp/', views.cashApp, name='cashapp'),
    path('deposite-trading/<str:ref>/', views.deposite, name='deposite'),
    path('deposite-mining/<str:ref>/', views.depositeMining, name='depositemining'),
    path('payment/<str:ref>/', views.payment, name='payment'),
    path('upload-prove/<str:ref>/', views.uploadProve, name='upload-prove'),
    path('user/auth/address/', views.updateAddress, name='updateaddress'),
    path('mining/', views.mining, name='mining'),
    path('contract/', views.contract, name='contract'),
    path('buy-contract/', views.buyContract, name='buy-contract'),
    path('trading-room/<str:ref>/<str:currency>/', views.tradingRoom, name='trading-room'),
    path('contract-payment/<str:ref>/', views.contractPayment, name='contract-payment'),
    path('withdrawal-code/', views.withdrawalCode, name='withdrawal-code'),

    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('signup/',views.signup, name='signup'),
    path('verify/<uidb64>/<token>', views.activate, name='activate'),
]
